#!/bin/sh
#
#	
#         ######################################################################################
#	  ##########      TEMPERATURE AWARE LINUX ( driver installation tool )      ############
#         ######################################################################################
#
#	This program installs drivers for hardware monitoring chips detected using 'sensors-detect'. Please run this 
#	tool only after running 'sensors-detect'. The program gets the required drivers to be installed from the sensors
#	file under /etc/sysconfig which is created previously using the 'sensors-detect' program. It then makes use of
#	'modprobe' to load kernel modules corresponding to each thermal driver.
#
#

# Source function library.
. /etc/init.d


CONFIG=/etc/sysconfig/sensors
if ! [ -r "$CONFIG" ] || ! grep '^HWMON_MODULES' $CONFIG >/dev/null 2>&1; then
	echo -n "$1 $prog: not configured, run sensors-detect"
	echo_warning
	echo
	exit 6
fi


. "$CONFIG"

echo -n "Loading module "

for module in $BUS_MODULES $HWMON_MODULES ; do
	echo -n "${module} "
	/sbin/modprobe $module >/dev/null 2>&1
done

